//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MSG_PLATFORM.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MSG_PLATFORM_DIALOG         102
#define IDD_DLG_LOAD                    102
#define IDR_MAINFRAME                   128
#define IDB_HOMEPAGE                    129
#define IDD_DLG_XXGL                    136
#define IDD_DLG_YYGL                    137
#define IDD_DLG_YHGL                    138
#define IDD_DLG_XXCL                    139
#define IDD_DLG_PLATFORM                142
#define IDB_HOMEPAGE_POLICY             143
#define IDB_HOMEPAGE_MSG                144
#define IDB_HOMEPAGE_APP                145
#define IDB_HOMEPAGE_USER               146
#define IDB_HOMEPAGE_EXTAPP             147
#define IDR_MENU_MSG_2                  149
#define IDB_BTN_MENU_DOWN               152
#define IDB_BTN_MENU_NORMAL             155
#define IDB_BTN_MENU_FOCUS              156
#define IDB_BTN_MENU_DISABLE            157
#define IDB_BMP_LOAD                    161
#define IDD_DLG_USERINFO                162
#define IDD_DLG_UNITINFO                163
#define IDI_TREE_ROOT                   164
#define IDI_TREE_LEAF_SELECT            165
#define IDI_TREE_LEAF                   166
#define IDI_TREE_NODE                   167
#define IDI_ICON3                       169
#define IDI_ICON1                       171
#define IDI_USER                        171
#define IDD_DLG_APPINFO                 172
#define IDB_HOME_XXCL                   177
#define IDB_HOME_WBYY                   179
#define IDB_HOME_XXGL                   180
#define IDB_HOME_YYGL                   181
#define IDB_HOME_YHGL                   182
#define IDD_DLG_APPMESSAGE              183
#define IDD_DLG_WBYY                    185
#define IDI_EXT_APP                     186
#define IDI_SYS_APP                     187
#define IDI_LIST_APP                    188
#define IDD_DLG_APPITEM                 189
#define IDD_DLG_APPFLOW                 190
#define IDI_LIST_ITEM                   192
#define IDB_MSG_SYS                     236
#define IDB_MSG_APP                     237
#define IDB_MSG_USER                    238
#define IDR_MENU_MSG                    239
#define IDR_MENU_MSG_1                  240
#define IDC_BTN_XXGL                    1000
#define IDC_BTN_MSGTYPE                 1000
#define IDC_BTN_STORAGE                 1000
#define IDC_BTN_YHGL                    1001
#define IDC_BTN_QUERY                   1001
#define IDC_BTN_EDIT                    1001
#define IDC_BTN_YYGL                    1002
#define IDC_BTN_DELETE                  1002
#define IDC_BTN_XXCL                    1003
#define IDC_BTN_VIEW                    1003
#define IDC_BTN_XTSZ                    1004
#define IDC_BTN_MSGQUERY                1004
#define IDC_BTN_WBYY                    1004
#define IDC_BTN_TJFX                    1005
#define IDC_BTN_DELUNIT                 1005
#define IDC_STATIC_DATA                 1006
#define IDC_SHOW_AREA                   1006
#define IDC_BTN_DELUSER                 1006
#define IDC_LIST_MSG                    1008
#define IDC_BTN_DISPATCH                1009
#define IDC_BTN_MSGCLASS                1009
#define IDC_BUTN_QUERY                  1009
#define IDC_BTN_CREATAPP                1009
#define IDC_BTN_MSGDISPATCH             1009
#define IDC_BTN_SENDMSG                 1010
#define IDC_BTN_MSGCLASS2               1010
#define IDC_BTN_MSGHISTORY              1010
#define IDC_BTN_DELETEAPP               1011
#define IDC_BTN_REFLASH                 1012
#define IDC_BTN_SELECT                  1013
#define IDC_AREA_MENU1                  1022
#define IDC_AREA_MENU2                  1023
#define IDC_AREA_GRID                   1024
#define IDC_BTN_AUDIT                   1025
#define IDC_AREA_GRID2                  1025
#define IDC_BTN_NOTAUDIT                1026
#define IDC_BTN_FORBIT                  1026
#define IDC_BTN_PASS                    1027
#define IDC_TREE_UNIT                   1028
#define IDC_LIST_USER                   1029
#define IDC_EDIT_KEYWORD                1030
#define IDC_BTN_ADDUNIT                 1031
#define IDC_BTN_MODIFYUNIT              1032
#define IDC_BTN_ADDUSER                 1033
#define IDC_BTN_MODIFYUSER              1034
#define IDC_EDIT_USERNAME               1035
#define IDC_EDIT_PASSWORD               1036
#define IDC_EDIT_USERID                 1036
#define IDC_EDIT_PWD                    1037
#define IDC_EDIT_NAME                   1038
#define IDC_RDO_SEX_1                   1039
#define IDC_RDO_SEX_2                   1040
#define IDC_CMB_RIGHT                   1041
#define IDC_EDIT_MANAGER                1042
#define IDC_EDIT_TELEPHONE              1042
#define IDC_EDIT_SUPERNAME              1043
#define IDC_EDIT_EMAIL                  1043
#define IDC_EDIT_UNITID                 1044
#define IDC_EDIT_NAME2                  1044
#define IDC_EDIT_WEIXIN                 1044
#define IDC_EDIT_UNITNAME               1045
#define IDC_EDIT_RANK                   1046
#define IDC_RADIO1                      1047
#define IDC_RAD_PASS                    1047
#define IDC_RDO_AUTOEXECUTE1            1047
#define IDC_RADIO2                      1048
#define IDC_RAD_NOPASS                  1048
#define IDC_RDO_AUTOEXECUTE2            1048
#define IDC_RDO_SENDMSG1                1049
#define IDC_EDIT_APPNAME                1050
#define IDC_RDO_SENDMSG2                1050
#define IDC_CMB_APPTYPE                 1051
#define IDC_EDIT_ICONPATH               1052
#define IDC_EDIT3                       1053
#define IDC_EDIT_REMARK                 1053
#define IDC_EDIT_ORDER                  1053
#define IDC_BTN_SELECTPATH              1054
#define IDC_EDIT_APPID                  1055
#define IDC_EDIT_TITLE                  1056
#define IDC_EDIT_CONTENT                1057
#define IDC_EDIT_PHONE                  1057
#define IDC_LIST_EXTAPP                 1058
#define IDC_BTN_MNSENDMSG               1059
#define IDC_LIST_ITEM                   1060
#define IDC_LIST_FLOW                   1061
#define IDC_BTN_ADDITEM                 1062
#define IDC_BTN_DELITEM                 1063
#define IDC_BTN_ADDFLOW                 1064
#define IDC_EDIT_ITEMNAME               1064
#define IDC_BTN_DELFLOW                 1065
#define IDC_EDIT_FLOWNAME               1066
#define IDC_EDIT_PROMPT                 1067
#define IDC_EDIT_MESSAGE                1068
#define IDC_CHK_SENDTYPE1               1069
#define IDC_CHK_SENDTYPE2               1070
#define IDC_LIST_KEYWORD                1070
#define IDC_CHK_SENDTYPE3               1071
#define IDC_CHK_SENDTYPE4               1072
#define IDC_BTN_ADDKEYW                 1072
#define IDC_BTN_DELKEYW                 1073
#define IDC_CHK_SYSMSG1                 1074
#define IDC_CHK_SYSMSG2                 1075
#define IDC_CHK_SYSMSG3                 1076
#define IDC_CHK_SYSMSG4                 1077
#define IDC_CHK_APPMSG1                 1078
#define IDC_CHK_APPMSG2                 1079
#define IDC_CHK_APPMSG3                 1080
#define IDC_CHK_APPMSG4                 1081
#define IDC_CHK_USERMSG1                1082
#define IDC_CHK_USERMSG2                1083
#define IDC_CHK_USERMSG3                1084
#define IDC_CHK_USERMSG4                1085
#define IDC_BTN_MODIFY                  1087
#define IDC_EDIT_APPLIMIT               1088
#define IDC_EDIT_USERLIMIT              1089
#define IDC_CMD_INITSCORE               1090
#define IDC_CMB_SUBSCORE                1092
#define IDC_APP_PASS                    10002
#define IDC_APP_AUDIT                   10003
#define IDC_APP_FORBID                  10004
#define IDM_MSG_USER                    32773
#define IDM_MSG_APP                     32774
#define IDM_MSG_ALL                     32775
#define ID_CATEMSG_MENU1                32776
#define ID_CATEMSG_MENU2                32777
#define IDM_MSG_STORAGE                 32778
#define IDM_MSG_DISPATCH                32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
